# Generated by Django 4.1.7 on 2023-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BG_Add_Remove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('back_image', models.ImageField(blank=True, upload_to='background_images')),
                ('bg_image', models.ImageField(blank=True, upload_to='bg_images/')),
            ],
        ),
    ]
