# Generated by Django 4.1.7 on 2023-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bg_add_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bg_add_color',
            old_name='color',
            new_name='b',
        ),
        migrations.AddField(
            model_name='bg_add_color',
            name='g',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bg_add_color',
            name='r',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
