# Generated by Django 4.1.7 on 2023-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_color_bg_add_color_b_bg_add_color_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_add_remove',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
