# Generated by Django 4.1.7 on 2023-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bg_add_remove_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_add_color',
            name='hex_color',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bg_add_color',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
