# Generated by Django 4.1.7 on 2023-04-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bg_add_color_hex_color_alter_bg_add_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bg_add_color',
            name='b',
        ),
        migrations.RemoveField(
            model_name='bg_add_color',
            name='g',
        ),
        migrations.RemoveField(
            model_name='bg_add_color',
            name='r',
        ),
    ]
