# Generated by Django 4.1.7 on 2023-11-16 08:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imagegallery_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(limit_choices_to={'image__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='core.imagegallery'),
        ),
    ]
