# Generated by Django 4.1.7 on 2023-11-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blog_description_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(limit_choices_to={'image__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='core.imagegallery'),
        ),
    ]
