# Generated by Django 4.1.7 on 2024-01-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_analyticsscript_webmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_add_color',
            name='webp_bg_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bg_add_remove',
            name='webp_bg_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bg_remove',
            name='webp_bg_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bg_remove',
            name='webp_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
