# Generated by Django 4.1.7 on 2024-01-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bg_add_color_webp_bg_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
