# Generated by Django 4.1.7 on 2024-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_imagegallery_webp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_remove',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
